name: Example key vault flow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@v2
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: 'AzureChinaCloud'
    - uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: "wingtiptoyskeyvault"
        secrets: 'ywttest, test05'
      id: myGetSecretAction
    - run: |
        echo ${{steps.myGetSecretAction.outputs.ywttest}}
   
